// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNtNG6fN5OnszJRgdOBo5CL3zRmzJpGaY',
    appId: '1:123456789:web:abcdefghijklmnopqrstuvwxyz',
    messagingSenderId: '123456789',
    projectId: 'mend-ai-dev',
    authDomain: 'mend-ai-dev.firebaseapp.com',
    storageBucket: 'mend-ai-dev.appspot.com',
    measurementId: 'G-ABCDEFGHIJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeHUDm_gunWYFPBie-usFeFUocLFR6mqs',
    appId: '1:867447335283:android:b915317252461702cafd06',
    messagingSenderId: '867447335283',
    projectId: 'mend-ai-616af',
    databaseURL: 'https://mend-ai-616af-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mend-ai-616af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH0Zf-TEArRq3zmknMRqVBgVx6irbAF4M',
    appId: '1:867447335283:ios:b1257ba27f4ba959cafd06',
    messagingSenderId: '867447335283',
    projectId: 'mend-ai-616af',
    databaseURL: 'https://mend-ai-616af-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mend-ai-616af.firebasestorage.app',
    iosClientId: '867447335283-k5mnj7vib7itao0u93i6bveo9pvcovgk.apps.googleusercontent.com',
    iosBundleId: 'com.example.mendAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNtNG6fN5OnszJRgdOBo5CL3zRmzJpGaY',
    appId: '1:123456789:ios:abcdefghijklmnopqrstuvwxyz',
    messagingSenderId: '123456789',
    projectId: 'mend-ai-dev',
    storageBucket: 'mend-ai-dev.appspot.com',
    iosClientId: '123456789-abcdefghijklmnopqrstuvwxyz.apps.googleusercontent.com',
    iosBundleId: 'com.example.mendAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNtNG6fN5OnszJRgdOBo5CL3zRmzJpGaY',
    appId: '1:123456789:web:abcdefghijklmnopqrstuvwxyz',
    messagingSenderId: '123456789',
    projectId: 'mend-ai-dev',
    authDomain: 'mend-ai-dev.firebaseapp.com',
    storageBucket: 'mend-ai-dev.appspot.com',
    measurementId: 'G-ABCDEFGHIJ',
  );
}